name: Publish to NPM

on:
  release:
    types: [published]

permissions:
  id-token: write
  contents: read

jobs:
  quality-checks:
    name: Pre-publish Quality Checks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Upgrade npm to latest
        run: npm install -g npm@latest
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: latest
          run_install: false

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: 'pnpm'
          cache-dependency-path: pnpm-lock.yaml

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run TypeScript check
        run: pnpm run typecheck

      - name: Run linter
        run: pnpm run lint

      - name: Run tests
        run: pnpm test
      - name: Build library
        run: pnpm run build

      - name: Check package contents
        run: pnpm pack

  publish-npm:
    name: Publish to NPM Registry
    needs: quality-checks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Upgrade npm to latest
        run: npm install -g npm@latest
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: latest
          run_install: false

      - name: Setup Node.js with NPM registry
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          registry-url: 'https://registry.npmjs.org'
          cache: 'pnpm'
          cache-dependency-path: pnpm-lock.yaml

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build library
        run: pnpm run build

      - name: Publish to NPM
        run: |
          # Determine tag from release (beta, alpha, etc.)
          TAG="latest"
          if [[ "${{ github.event.release.prerelease }}" == "true" ]]; then
            TAG="next"
          fi

          echo "Publishing with tag: $TAG"
          pnpm publish --access public --tag $TAG --no-git-checks
